In [2]:
import numpy as np
import os
exists = os.path.exists

In [29]:
#read ada
p = r'G:\f\SJTUstudy\G3_SEMESTER2\machine_learning\hw3\datasets_raw\usps\tr.t'
exists(p)

True

In [8]:
print(a1a_tr[0].shape, a1a_tr[1].shape)
print(a1a_te[0].shape, a1a_te[1].shape)


(1605, 123) (1605,)
(30956, 123) (30956,)


In [7]:
a1a_tr, a1a_te = read_dataset_A(DatasetsA.a1a)
a7a_tr, a7a_te = read_dataset_A(DatasetsA.a7a)

In [27]:
from sklearn.preprocessing import minmax_scale

In [4]:
from Ldata_helper import *
from Lglobal_defs import *

In [2]:
from sklearn.svm import SVC

In [27]:
clf = SVC(max_iter=100,gamma='auto')
clf.fit(a1a_tr[0],a1a_tr[1])
tr_p = clf.predict(a1a_tr[0][:10])
te_p = clf.predict(a1a_te[0][:10])
print(tr_p, a1a_tr[1][:10])
print(te_p, a1a_te[1][:10])
from sklearn.metrics import *
print(accuracy_score(a1a_te[1][:10], te_p))
print(precision_score(a1a_te[1][:10], te_p))
print(recall_score(a1a_te[1][:10], te_p))
print(f1_score(a1a_te[1][:10], te_p))

[0 0 0 0 0 0 0 0 0 1] [0 0 0 0 0 0 0 0 0 1]
[1 0 0 0 1 0 0 0 1 0] [0 0 0 0 0 0 1 1 1 1]
0.5
0.3333333333333333
0.25
0.28571428571428575


In [15]:
precision_score

[1 1 1] [0 0 0]


In [1]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('mnist_data', one_hot=True)
mnist.test

D:\VS2017\Shared\Anaconda3_64\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting mnist_data\train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting mnist_data\train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting mnist_data\t10k-images-idx3-ubyte.gz
Extracting mnist_data\t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [6]:
print(mnist.test.labels.shape)
print(mnist.train.labels.shape)
print(mnist.test.images.shape)
print(mnist.train.images.shape)

(10000, 10)
(55000, 10)
(10000, 784)
(55000, 784)


In [7]:
def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

In [8]:
d = unpickle(r'datasets_raw\cifar10\cifar-10-batches-py\data_batch_1')

In [9]:
d[b'batch_label']

{b'batch_label': b'training batch 1 of 5',
 b'labels': [6,
  9,
  9,
  4,
  1,
  1,
  2,
  7,
  8,
  3,
  4,
  7,
  7,
  2,
  9,
  9,
  9,
  3,
  2,
  6,
  4,
  3,
  6,
  6,
  2,
  6,
  3,
  5,
  4,
  0,
  0,
  9,
  1,
  3,
  4,
  0,
  3,
  7,
  3,
  3,
  5,
  2,
  2,
  7,
  1,
  1,
  1,
  2,
  2,
  0,
  9,
  5,
  7,
  9,
  2,
  2,
  5,
  2,
  4,
  3,
  1,
  1,
  8,
  2,
  1,
  1,
  4,
  9,
  7,
  8,
  5,
  9,
  6,
  7,
  3,
  1,
  9,
  0,
  3,
  1,
  3,
  5,
  4,
  5,
  7,
  7,
  4,
  7,
  9,
  4,
  2,
  3,
  8,
  0,
  1,
  6,
  1,
  1,
  4,
  1,
  8,
  3,
  9,
  6,
  6,
  1,
  8,
  5,
  2,
  9,
  9,
  8,
  1,
  7,
  7,
  0,
  0,
  6,
  9,
  1,
  2,
  2,
  9,
  2,
  6,
  6,
  1,
  9,
  5,
  0,
  4,
  7,
  6,
  7,
  1,
  8,
  1,
  1,
  2,
  8,
  1,
  3,
  3,
  6,
  2,
  4,
  9,
  9,
  5,
  4,
  3,
  6,
  7,
  4,
  6,
  8,
  5,
  5,
  4,
  3,
  1,
  8,
  4,
  7,
  6,
  0,
  9,
  5,
  1,
  3,
  8,
  2,
  7,
  5,
  3,
  4,
  1,
  5,
  7,
  0,
  4,
  7,
  5,
  5,
  1,
  0,
  9,
  6,
  9,
 

In [11]:
d.keys()

dict_keys([b'batch_label', b'labels', b'data', b'filenames'])

In [14]:
len(d[b'labels'])

10000

In [15]:
d[b'data'].shape

(10000, 3072)

In [16]:
d[b'data'][:2]

array([[ 59,  43,  50, ..., 140,  84,  72],
       [154, 126, 105, ..., 139, 142, 144]], dtype=uint8)

In [18]:
import numpy as np
np.max(d[b'data'][:2])

255

In [22]:
data = d[b'data']
data = (data / 256.0).astype(np.uint8)

In [21]:
data[:2]

array([[0.23046875, 0.16796875, 0.1953125 , ..., 0.546875  , 0.328125  ,
        0.28125   ],
       [0.6015625 , 0.4921875 , 0.41015625, ..., 0.54296875, 0.5546875 ,
        0.5625    ]])

In [1]:
import csv
p = r'G:\f\SJTUstudy\G3_SEMESTER2\machine_learning\hw3\datasets_raw\admissions\Admission_Predict.csv'

In [2]:
csvfn = csv.reader(open(p,'r'))

In [3]:
i = 0
for l in csvfn:
    i += 1
print(i)

401


In [8]:
import numpy as np

def csvfile2nparr(csvfn):
    csvfn = csvfilename(csvfn)
    csvfn = csv.reader(open(csvfn,'r'))
    def read_line(line):
        try:
            return [float(i) for i in line]
        except:
            return None
    m = [read_line(line) for line in csvfn]
    m = [l for l in m if l is not None]
    return np.array(m)

In [9]:
a = csvfile2nparr(p)

In [6]:
def posfix_filename(filename, postfix):
    if not filename.endswith(postfix):
        filename += postfix
    return filename


def npfilename(filename):
    return posfix_filename(filename, '.npy')


def pkfilename(filename):
    return posfix_filename(filename, '.pkl')


def csvfilename(filename):
    return posfix_filename(filename, '.csv')


def h5filename(filename):
    return posfix_filename(filename, '.h5')

In [97]:
print(data_w)
print(data)
print(np.matmul(data_w.T,data_w))

[[-1.86  -0.251  0.367 ...  0.111 -0.473  0.547]
 [-0.544  1.076 -1.091 ... -0.421  0.27   0.737]
 [ 0.147  0.863 -0.103 ... -1.052  1.634 -1.155]
 ...
 [-1.434 -1.84  -0.477 ... -0.123 -0.11   0.31 ]
 [ 0.455  0.517 -2.159 ...  1.514  0.692 -0.478]
 [-0.967 -0.233 -0.484 ...  2.111  0.451 -0.306]]
[[337.   118.     4.   ...   9.65   1.     0.92]
 [324.   107.     4.   ...   8.87   1.     0.76]
 [316.   104.     3.   ...   8.     1.     0.72]
 ...
 [330.   120.     5.   ...   9.56   1.     0.93]
 [312.   103.     4.   ...   8.43   0.     0.73]
 [327.   113.     4.   ...   9.04   0.     0.84]]
[[499.  -0.   0.   0.  -0.   0.   0.   0.]
 [ -0. 499.   0.   0.  -0.   0.  -0.  -0.]
 [  0.   0. 499.  -0.  -0.   0.   0.   0.]
 [  0.   0.  -0. 499.  -0.   0.   0.  -0.]
 [ -0.  -0.  -0.  -0. 499.   0.  -0.  -0.]
 [  0.   0.   0.   0.   0. 499.   0.  -0.]
 [  0.  -0.   0.   0.  -0.   0. 499.  -0.]
 [  0.  -0.   0.  -0.  -0.  -0.  -0. 499.]]


In [1]:
from Ldata_helper import *
from Lglobal_defs import *
from test_lingam import *
import numpy as np

D:\VS2017\Shared\Anaconda3_64\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [17]:
from Ldata_helper import *
from Lglobal_defs import *
from test_lingam import *
data = read_dataset_2(Datasets2.admissions)
b = estimate(data)

In [114]:
np.set_printoptions(precision=3,suppress=True)
data_w = PCA(n_components=None, whiten=True).fit_transform(data)
data_mw = PCA(n_components=None, whiten=True).fit_transform(data_m)
b_m = estimate(data_m,random_state=1)
b = estimate(data,random_state=1)
b_mw = estimate(data_mw,random_state=1)
b_w = estimate(data_w,random_state=1)

In [5]:
data = read_dataset_2(Datasets2.diamonds)
np.set_printoptions(precision=2,suppress=True)
b = estimate(data[:,:-2],random_state=1)
# print("GREScore,TOEFLScore,Univ,   SOP,    LOR,   CGPA,   Research,Admit")
#print('hour,   Mild, Serious, victims, vehicles')

print(b)
b = estimate(data[:40000,:-2],random_state=1)
print(b)

[[   0.      0.      0.      0.      0.      0.      0.      0.  ]
 [  -0.64    0.      0.      0.      0.      0.      0.      0.  ]
 [   2.51    0.06    0.      0.      0.      0.      0.      0.  ]
 [  -2.55   -0.05    0.3     0.      0.      0.      0.      0.  ]
 [   0.5    -1.07   -0.      0.08    0.      0.      0.      0.  ]
 [  -0.37   -0.06    0.06   -0.38   -0.58    0.      0.      0.  ]
 [8658.26  118.43  -91.81  155.98  -47.23   -2.89    0.   -635.51]
 [   1.1    -0.02    0.02    0.01   -0.05   -0.02    0.      0.  ]]
[[   0.      0.      0.      0.      0.      0.      0.      0.  ]
 [  -0.49    0.      0.      0.      0.      0.      0.      0.  ]
 [   2.58    0.08    0.      0.      0.      0.      0.      0.  ]
 [  -3.49   -0.07    0.29    0.      0.      0.      0.      0.  ]
 [   0.52   -1.06   -0.      0.07    0.      0.      0.      0.  ]
 [  -0.59   -0.02    0.08   -0.37   -0.52    0.      0.      0.  ]
 [8020.79  148.06 -101.49  168.12  -42.9    -1.21    0.   -28

In [191]:
n=100000
x1 = np.random.uniform(0.0,1.0,[n])
x2 = np.random.uniform(1.0,10.0,[n])
x3 = np.random.uniform(-0.5,0.0,[n])
x4 = np.random.uniform(-50.0,-1.0,[n])
e1 = np.random.uniform(85.0,100.0,[n])
e2 = np.random.uniform(0.0,1.0,[n])
y1 = 0.5*x1 + e1
y2 = x2 + 2*x3 + e2
d = np.vstack([x1,x2,x3,x4,y1,y2]).T
d2 = np.vstack([y2,x2,x3,x4,y1,x1]).T
#d2 = MinMaxScaler().fit_transform(d)
b_d = estimate(d,random_state=100)
print(b_d)
b_d = estimate(d,random_state=10000)
print(b_d)
b_d = estimate(d,random_state=0)
print(b_d)
#b_2 = estimate(d2,random_state=100)
#print(b_2)

[[ 0.     0.     0.     0.     0.     0.   ]
 [ 0.017  0.    -0.036  0.     0.     0.   ]
 [-0.002  0.     0.     0.     0.     0.   ]
 [ 0.151 -0.085 -0.252  0.     0.     0.085]
 [ 0.527 -0.041 -0.068 -0.     0.     0.037]
 [-0.003  1.     2.003  0.     0.     0.   ]]
[[ 0.     0.     0.     0.     0.     0.   ]
 [ 0.017  0.    -0.036  0.     0.     0.   ]
 [-0.002  0.     0.     0.     0.     0.   ]
 [ 0.151 -0.085 -0.252  0.     0.     0.085]
 [ 0.527 -0.041 -0.067 -0.     0.     0.037]
 [-0.003  1.     2.003  0.     0.     0.   ]]
[[ 0.     0.     0.     0.     0.     0.   ]
 [ 0.017  0.    -0.036  0.     0.     0.   ]
 [-0.002  0.     0.     0.     0.     0.   ]
 [ 0.151 -0.085 -0.25   0.     0.     0.085]
 [ 0.527 -0.041 -0.067 -0.     0.     0.037]
 [-0.003  1.     2.003  0.     0.     0.   ]]


In [173]:
x1 = np.random.uniform(0.0,1.0,[100])
x2 = np.random.uniform(1.0,3.0,[100])
x3 = np.random.uniform(-0.5,0.0,[100])
x4 = np.random.uniform(-5.0,-1.0,[100]) * 0.01
e = np.array([])
y1 = 0.5*x1 + e1
y2 = x2 + 2*x3 + e2
d = np.vstack([x1,x2,x3,x4,y1,y2]).T
d2 = np.vstack([y2,x2,x3,x4,y1,x1]).T
d2 = MinMaxScaler().fit_transform(d)
b_d = estimate(d,random_state=1)
print(b_d)
b_2 = estimate(d2,random_state=1)
print(b_2)

[[ 0.     0.    -0.786  0.376  0.     0.   ]
 [ 0.16   0.    -1.064  1.515  0.     0.   ]
 [ 0.     0.     0.     2.998  0.     0.   ]
 [ 0.     0.     0.     0.     0.     0.   ]
 [ 0.406  4.518  2.395 33.337  0.    -2.894]
 [-0.215  0.999  2.763 -0.152  0.     0.   ]]
[[ 0.     0.086  0.358 -0.291  0.051 -0.377]
 [ 0.     0.     0.032 -0.33   0.359  0.   ]
 [ 0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.    -0.042  0.     0.     0.   ]
 [ 0.     0.     0.077  0.061  0.     0.   ]
 [ 0.     0.71   0.308 -0.05  -0.015  0.   ]]


In [132]:
print(d2[:10])
print(d[:10])

[[2.631 0.743 0.716 0.306 0.565]
 [4.173 1.99  0.974 0.493 0.592]
 [3.139 1.194 0.775 0.407 0.466]
 [3.307 1.217 0.956 0.574 0.958]
 [2.527 0.043 0.995 0.071 0.044]
 [2.423 0.648 0.835 0.38  0.675]
 [1.651 0.161 0.566 0.102 0.021]
 [1.445 0.074 0.512 0.458 0.887]
 [2.108 0.436 0.591 0.392 0.728]
 [1.861 0.149 0.657 0.283 0.221]]
[[0.565 0.743 0.716 0.306 2.631]
 [0.592 1.99  0.974 0.493 4.173]
 [0.466 1.194 0.775 0.407 3.139]
 [0.958 1.217 0.956 0.574 3.307]
 [0.044 0.043 0.995 0.071 2.527]
 [0.675 0.648 0.835 0.38  2.423]
 [0.021 0.161 0.566 0.102 1.651]
 [0.887 0.074 0.512 0.458 1.445]
 [0.728 0.436 0.591 0.392 2.108]
 [0.221 0.149 0.657 0.283 1.861]]


In [72]:
bb

array([[ 0.   , -0.16 , -0.508],
       [ 0.   ,  0.   , -0.222],
       [ 0.   ,  0.   ,  0.   ]])

In [45]:
bb

array([[ 0.   ,  0.   ,  0.   ],
       [ 0.04 ,  0.   , -0.219],
       [ 0.507,  0.   ,  0.   ]])

In [169]:
from sklearn.preprocessing import *
a = np.array([[1,2,0],[-5,-4,1],[9,4,1]])
print(a)
print(MinMaxScaler().fit_transform(a))

[[ 1  2  0]
 [-5 -4  1]
 [ 9  4  1]]
[[0.429 0.75  0.   ]
 [0.    0.    1.   ]
 [1.    1.    1.   ]]


D:\VS2017\Shared\Anaconda3_64\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


[[0.429 0.75  0.   ]
 [0.    0.    1.   ]
 [1.    1.    1.   ]]


D:\VS2017\Shared\Anaconda3_64\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64.
  warnings.warn(msg, DataConversionWarning)


In [60]:
from sklearn.preprocessing import *
from sklearn.decomposition import *

In [61]:
print(a)

[[ 1  2  0]
 [-5 -4  1]
 [ 9  4  1]]


In [101]:
m = np.mean(data,0)
print(m)
data_m = data-m

[316.472 107.192   3.114   3.374   3.484   8.576   0.56    0.722]


In [103]:
np.mean(data_m,0)

array([ 0., -0., -0., -0.,  0.,  0.,  0., -0.], dtype=float32)

In [116]:
print(12)

12
